# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
exclude: |
  (?x)^(
    tofu/.terraform/.*
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
  rev: v1.0
  hooks:
    - id: sops-encryption
      files: ((^|/)sops.y[a]{0,1}ml$)
