- name: Prepares the Proxmox nodes
  hosts:
    - proxmox
  gather_facts: true
  become: true
  tags: bootstrap
  vars_files:
    - vars/{{ ansible_os_family }}.yml
  roles:
    - wake
    - buluma.bootstrap
    - geerlingguy.ntp
    - geerlingguy.pip
  tasks:
    - name: Update hostname
      tags: hostname
      block:
        - name: Set correct hostname and domain
          ansible.builtin.hostname:
            name: "{{ inventory_hostname }}.{{ pve_domain }}"

        - name: Set hostname to /etc/hostname
          ansible.builtin.lineinfile:
            path: /etc/hostname
            line: "{{ inventory_hostname }}"

        - name: Update /etc/hosts
          ansible.builtin.replace:
            dest: /etc/hosts
            regexp: "^({{ ansible_default_ipv4.address }}.*)$"
            replace: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}.{{ pve_domain }} {{ inventory_hostname }}"
            backup: true

        - name: Update search-domain in /etc/resolv.conf
          ansible.builtin.replace:
            dest: /etc/resolv.conf
            regexp: "^search.*$"
            replace: "search {{ pve_domain }}"
            backup: true

        - name: Symlink /etc/ntp.conf to ntp_config_file
          ansible.builtin.file:
            src: "{{ ntp_config_file }}"
            dest: /etc/ntp.conf
            state: link
            force: true
          when: ntp_config_file != '/etc/ntp.conf'

- name: Provision Proxmox on nodes
  hosts:
    - proxmox
  gather_facts: true
  become: true
  tags:
    - provision
  vars_files:
    - vars/{{ ansible_os_family }}.yml
  roles:
    - name: lae.proxmox
      tags: pve
    #- name: caddy
    #  tags: caddy
    #- name: keepalived
    #  tags: keepalived
  tasks:
    - name: Validate api token
      ansible.builtin.shell:
        cmd: pveum user token list '{{ vault_pve_api_token_user }}@{{ vault_pve_api_token_user_realm }}' | grep -q "{{ vault_pve_api_token_id }}"
      register: api_token_validation
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Generate proxmox API token
      when: api_token_validation.rc == 1
      run_once: true
      block:
        - name: Add api token for Ansible-user to Proxmox
          ansible.builtin.shell:
            cmd: >-
              set -o pipefail &&
              pveum user token add '{{ vault_pve_api_token_user }}@{{ vault_pve_api_token_user_realm }}'
              '{{ vault_pve_api_token_id }}' --privsep 0 --output-format json
            executable: /bin/bash
          register: token_msg
          changed_when: true
          become: true

        - name: Print Ansible API token
          ansible.builtin.debug:
            msg: '{{ token_data | json_query(''"full-tokenid"'') }}={{ token_data | json_query("value") }}'
          vars:
            - token_data: "{{ token_msg.stdout | from_json }}"
