- name: Get Proxmox information
  hosts:
    - proxmox
  gather_facts: true
  vars_files:
    - vars/{{ ansible_os_family }}.yml
  tasks:
    - name: List existing nodes
      community.general.proxmox_node_info:
        api_host: "{{ ansible_host }}"
        api_user: "{{ vault_pve_api_token_user }}@{{ vault_pve_api_token_user_realm }}"
        api_token_id: "{{ vault_pve_api_token_id }}"
        api_token_secret: "{{ vault_pve_api_token_secret }}"
      register: proxmox_nodes

    - name: Debug
      ansible.builtin.debug:
        var: proxmox_nodes
