---
roles:
  - name: caddy_ansible.caddy_ansible
  - name: ironicbadger.proxmox_nag_removal
  - name: geerlingguy.ntp
  - name: lae.proxmox
  - name: geerlingguy.pip
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.netcommon
  - name: community.general
  - name: community.docker
