---
- name: Manage power state
  hosts: proxmox
  become: true
  gather_facts: false
  any_errors_fatal: true
  vars:
    ansible_host_key_checking: false
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 10
  tasks:
    - name: Power on host
      ansible.builtin.include_role:
        name: wake
      when: state == 'on'

    - name: Power off host
      community.general.shutdown:
        delay: 30
      when: state == 'off'
