# copy_pxelinux_template.yml

- name:  Copy PXElinux template
  ansible.builtin.template:
    src: "{{ pxe_server_templates[group]['pxelinux_file'] }}"
    dest: "{{ role_path }}/files/data/tftpboot/pxelinux.cfg/01-{{ hostvars[item]['mac'] | replace(':', '-') | lower }}"
    mode: 0644
  loop: "{{ matching_hosts }}"
  loop_control:
    loop_var: item

- name: Generate automated install template
  ansible.builtin.template:
    src: "{{ pxe_server_templates[group]['autoboot_file'] }}"
    dest: "{{ role_path }}/files/data/init-config/{{ hostvars[item]['mac'] | replace(':', '-') | lower }}.{{ pxe_server_templates[group]['autoboot_file'].split('.')[-2] }}"
    mode: 0644
  loop: "{{ matching_hosts }}"
