version: "3"

services:
  dnsmasq:
    image: pxe_files_dnsmasq
    build: ./dnsmasq
    volumes:
      - ./data/pxe-config/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/tftpboot:/tftp
    network_mode: host
    cap_add:
      - NET_ADMIN
  http:
    image: pxe_files_http
    build: ./http
    network_mode: host
    volumes:
      - ./data/tftpboot:/usr/share/nginx/html
    environment:
      NGINX_PORT: 80
