---
ansible_host: "{{inventory_hostname_short}}.{{ pve_domain }}"

# proxmox api stuff
pve_api_user_username: automation
pve_api_user_realm: pve
preseed_config: "{{ lookup('template', 'preseed-proxmox.j2') }}"

# geerlingguy.pip
pip_install_packages:
  - name: proxmoxer
    state: present

# lae.proxmox
pve_groups:
  - name: Admins
    comment: Homelab administrators
pve_users: "{{ proxmox_users }}"

pve_acls:
  - path: /
    roles: [ "Administrator" ]
    groups: [ "Admins" ]
